### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by saiwg** [WeBankBlockchain/Data-Stash#24]
2021-12-13 14:37:09.139  INFO 4732 --- [           main] c.w.b.data.stash.DataStashApplication    : Starting DataStashApplication on linux with PID 4732 (/fisco-bcos/Data-Stash/tools/Data-Stash.jar started by root in /fisco-bcos/Data-Stash/tools)
2021-12-13 14:37:09.141  INFO 4732 --- [           main] c.w.b.data.stash.DataStashApplication    : No active profile set, falling back to default profiles: default
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2021-12-13 14:37:11.013  INFO 4732 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-12-13 14:37:11.016  WARN 4732 --- [           main] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
2021-12-13 14:37:11.136  INFO 4732 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-12-13 14:37:11.693  INFO 4732 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2021-12-13 14:37:11.722  INFO 4732 --- [           main] c.w.b.data.stash.DataStashApplication    : Started DataStashApplication in 2.823 seconds (JVM running for 3.229)
2021-12-13 14:37:11.820  INFO 4732 --- [           main] c.w.b.d.stash.manager.DownloadManager    : Scan remote item 0, size: 3
2021-12-13 14:37:11.820  INFO 4732 --- [           main] c.w.b.d.stash.manager.DownloadManager    : Download start from last local file: 11240
2021-12-13 14:37:11.820  INFO 4732 --- [           main] c.w.b.d.stash.manager.DownloadManager    : Begin to download http://loclhost:5299/, binlog file: 11240 
2021-12-13 14:37:11.875  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Begin to start。。。。
2021-12-13 14:37:11.875  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：8 kB
2021-12-13 14:37:11.875  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：16 kB
2021-12-13 14:37:11.875  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：24 kB
2021-12-13 14:37:11.876  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：32 kB
2021-12-13 14:37:11.876  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：36.31 kB
Task download finished！
2021-12-13 14:37:11.891  INFO 4732 --- [           main] c.w.b.d.stash.manager.DownloadManager    : next to do is 11253
2021-12-13 14:37:11.891  INFO 4732 --- [           main] c.w.b.d.stash.manager.DownloadManager    : Begin to download http://loclhost:5299/, binlog file: 11253 
2021-12-13 14:37:11.970  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Begin to start。。。。
2021-12-13 14:37:11.970  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：8 kB
2021-12-13 14:37:11.970  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：16 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：24 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：32 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：40 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：48 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：56 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：64 kB
2021-12-13 14:37:11.971  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：72 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：80 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：88 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：96 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：104 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：112 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：120 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：128 kB
2021-12-13 14:37:11.972  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：136 kB
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：144 kB
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：152 kB
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：160 kB
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：168 kB
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：176 kB
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：177.59 kB
Task download finished！
2021-12-13 14:37:11.973  INFO 4732 --- [           main] c.w.b.d.stash.manager.DownloadManager    : Nothing to download.
2021-12-13 14:37:16.980  INFO 4732 --- [           main] c.w.b.d.stash.manager.BlockReadManager   : begin to insert block 0
2021-12-13 14:37:17.669 ERROR 4732 --- [           main] c.w.b.data.stash.handler.BlockHandler    : Exception occur: 

java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_292]
	at com.webank.blockchain.data.stash.utils.BytesUtil.subBytes(BytesUtil.java:50) ~[classes!/:na]
	at com.webank.blockchain.data.stash.parser.BlockBytesParser.processEntry(BlockBytesParser.java:154) ~[classes!/:na]
	at com.webank.blockchain.data.stash.parser.BlockBytesParser.processBlockData(BlockBytesParser.java:105) ~[classes!/:na]
	at com.webank.blockchain.data.stash.parser.BlockBytesParser.getBinlogBlockInfo(BlockBytesParser.java:65) ~[classes!/:na]
	at com.webank.blockchain.data.stash.parser.BlockBytesParser$$FastClassBySpringCGLIB$$324b2932.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at com.webank.blockchain.data.stash.aspect.UseTimeAspect.around(UseTimeAspect.java:43) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at com.webank.blockchain.data.stash.parser.BlockBytesParser$$EnhancerBySpringCGLIB$$740bfec7.getBinlogBlockInfo(<generated>) ~[classes!/:na]
	at com.webank.blockchain.data.stash.handler.BlockHandler.parseBinlogThenVerify(BlockHandler.java:65) ~[classes!/:na]
	at com.webank.blockchain.data.stash.manager.BlockReadManager.read(BlockReadManager.java:68) [classes!/:na]
	at com.webank.blockchain.data.stash.task.BinlogSyncTask.run(BinlogSyncTask.java:59) [classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at com.webank.blockchain.data.stash.DataStashApplication.main(DataStashApplication.java:23) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Data-Stash.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Data-Stash.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [Data-Stash.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [Data-Stash.jar:na]

2021-12-13 14:37:17.671  INFO 4732 --- [       Thread-2] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2021-12-13 14:37:17.672  INFO 4732 --- [       Thread-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-12-13 14:37:17.675  INFO 4732 --- [       Thread-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

FISCO-BCOS: original is 2.4.0, just upgraded to 2.8.0, and the binlog file are generated by version 2.4.0.
Data-Stach version is the latest

**Comment by arc0035** [comment]
Could you provide a sample binlog thus we can reproduce this issue?

**Comment by arc0035** [comment]
可以加我微信说明下情况 zookeeper6324 @saiwg

**Comment by arc0035** [comment]
经讨论是版本兼容问题，关闭了
