### ISSUE TITLE
Data-stash运行一段时间，程序意外退出，帮忙解读一下

### ISSUE THREAD

**Issue by ak-47-s** [WeBankBlockchain/Data-Stash#30]
2022-08-04 15:55:40.920  INFO 21119 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Begin to start。。。。
2022-08-04 15:55:40.920  INFO 21119 --- [           main] c.w.b.d.s.fetch.DefaultStreamProgress    : Already download：3.91 kB
Task download finished！
2022-08-04 15:55:40.920  INFO 21119 --- [           main] c.w.b.d.stash.manager.DownloadManager    : Nothing to download.
2022-08-04 15:55:45.922  INFO 21119 --- [           main] c.w.b.d.stash.manager.BlockReadManager   : begin to insert block 6
2022-08-04 15:55:45.933  INFO 21119 --- [           main] c.w.b.data.stash.aspect.UseTimeAspect    : com.webank.blockchain.data.stash.parser.BlockBytesParser@22fcf7ab use time 0
2022-08-04 15:55:45.934  INFO 21119 --- [    ledgerPool7] c.w.b.d.stash.store.LedgerTablesStorage  : storage ledger table name : _sys_hash_2_block_
2022-08-04 15:55:45.934  INFO 21119 --- [     statePool9] c.w.b.d.stash.store.StateTablesStorage   : storage state table: _sys_current_state_
2022-08-04 15:55:45.934  INFO 21119 --- [     statePool7] c.w.b.d.stash.store.StateTablesStorage   : storage state table: u_Evidence
2022-08-04 15:55:45.953  INFO 21119 --- [    ledgerPool7] c.w.b.d.stash.store.LedgerTablesStorage  : storage ledger table name : _sys_number_2_hash_
2022-08-04 15:55:45.953 ERROR 21119 --- [     statePool7] c.w.b.data.stash.handler.BlockHandler    : Exception occur: 

java.lang.ArrayIndexOutOfBoundsException: 2
	at com.webank.blockchain.data.stash.utils.ObjectBuildUtil.buildToDynamicObj(ObjectBuildUtil.java:73) ~[classes!/:na]
	at com.webank.blockchain.data.stash.convertor.DBEntryConvertor.convert(DBEntryConvertor.java:51) ~[classes!/:na]
	at com.webank.blockchain.data.stash.db.service.DBBaseOperation.batchConvert(DBBaseOperation.java:69) ~[classes!/:na]
	at com.webank.blockchain.data.stash.db.service.DBBaseOperation.storage(DBBaseOperation.java:49) ~[classes!/:na]
	at com.webank.blockchain.data.stash.db.service.DynamicTableInfoService.storeTableData(DynamicTableInfoService.java:57) ~[classes!/:na]
	at com.webank.blockchain.data.stash.db.service.DynamicTableInfoService$$FastClassBySpringCGLIB$$2bade4c9.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at com.webank.blockchain.data.stash.db.service.DynamicTableInfoService$$EnhancerBySpringCGLIB$$a2cf27fe.storeTableData(<generated>) ~[classes!/:na]
	at com.webank.blockchain.data.stash.store.StateTablesStorage.processSingleTable(StateTablesStorage.java:66) ~[classes!/:na]
	at com.webank.blockchain.data.stash.store.StateTablesStorage.lambda$null$1(StateTablesStorage.java:102) ~[classes!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]

2022-08-04 15:55:45.957  INFO 21119 --- [       Thread-2] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2022-08-04 15:55:45.961  INFO 21119 --- [       Thread-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-08-04 15:55:45.963  INFO 21119 --- [    ledgerPool7] c.w.b.d.stash.store.LedgerTablesStorage  : storage ledger table name : _sys_tx_hash_2_block_
2022-08-04 15:55:45.966  INFO 21119 --- [       Thread-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

**Comment by yingbaohuacumt** [comment]
KVTable合约数据转换时，fieldList[2].setAccessible(true) 数组越界异常，DynamicTableInfo类中只有2个成员

![image](https://user-images.githubusercontent.com/40226586/183953697-7db860e7-2979-419c-9999-edfb6a08ba49.png)

**Comment by arc0035** [comment]
用dev分支试一试，还不行可以提供下样例binlog

**Comment by yingbaohuacumt** [comment]
dev分支是ok的，以1.2.3分支为例，代码有bug，只要用了KVTable或Table在fisco平台AMDB建表了，binlog数据转换就数组越界

**Comment by arc0035** [comment]
嗯，这个分支我们近期会合并回main

**Comment by arc0035** [comment]
已发布到master分支，请再试下
