### ISSUE TITLE
Meeting the error when I excute start.sh

### ISSUE THREAD

**Issue by SeaCSKY** [WeBankBlockchain/Data-Stash#4]
2021-01-06 11:52:25.758  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : _sys_config_ in sys tables
2021-01-06 11:52:25.771  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : _sys_block_2_nonces_ in sys tables
2021-01-06 11:52:25.785  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : _sys_hash_2_header_ in sys tables
2021-01-06 11:52:25.799  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : c_3c9a57952c3f7e92b29911b306bd52a3d1531d1c in sys tables
2021-01-06 11:52:25.813  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : c_be29834f9c24c38592ffde749a1256927a59c9fd in sys tables
2021-01-06 11:52:25.827  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : c_07166d613996832fae6fd7c4d1cff6d44d9ef1e1 in sys tables
2021-01-06 11:52:25.840  INFO 20697 --- [main] c.w.b.d.s.db.rollback.RollBackService    : table name : c_8bb98b969b2ae878936292525308301f6d088894 in sys tables
2021-01-06 11:52:25.887  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : start to relocate, block number 25, item 0
2021-01-06 11:52:25.888  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Block 0 binlog length is 2395
2021-01-06 11:52:25.888  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Block 1 binlog length is 1
2021-01-06 11:52:25.889  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Block 2 binlog length is 469144998
2021-01-06 11:52:25.889  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : no new binlog content.
2021-01-06 11:52:25.899  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Latest block number 25, and the last offset is 100727, item 0
2021-01-06 11:52:25.923  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Block number 25, offset 100727, in file path of binlogcache/0/0.binlog, item 0
2021-01-06 11:52:25.923  INFO 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Block 25 binlog length is 4081
2021-01-06 11:52:26.335 ERROR 20697 --- [main] c.w.b.d.stash.manager.BlockReadManager   : Exception encounted: 

java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_275]
        at com.webank.blockchain.data.stash.utils.BytesUtil.subBytes(BytesUtil.java:50) ~[classes!/:na]
        at com.webank.blockchain.data.stash.parser.BlockBytesParser.processEntry(BlockBytesParser.java:153) ~[classes!/:na]
        at com.webank.blockchain.data.stash.parser.BlockBytesParser.processBlockData(BlockBytesParser.java:110) ~[classes!/:na]
        at com.webank.blockchain.data.stash.parser.BlockBytesParser.getBinlogBlockInfo(BlockBytesParser.java:70) ~[classes!/:na]
        at com.webank.blockchain.data.stash.parser.BlockBytesParser$$FastClassBySpringCGLIB$$324b2932.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at com.webank.blockchain.data.stash.aspect.UseTimeAspect.around(UseTimeAspect.java:44) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at com.webank.blockchain.data.stash.parser.BlockBytesParser$$EnhancerBySpringCGLIB$$a13fd23a.getBinlogBlockInfo(<generated>) ~[classes!/:na]
        at com.webank.blockchain.data.stash.handler.BlockHandler.handler(BlockHandler.java:68) ~[classes!/:na]
        at com.webank.blockchain.data.stash.manager.BlockReadManager.read(BlockReadManager.java:133) ~[classes!/:na]
        at com.webank.blockchain.data.stash.task.BinlogSyncTask.run(BinlogSyncTask.java:66) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at com.webank.blockchain.data.stash.DataStashApplication.main(DataStashApplication.java:23) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]

The bcos version is 2.7.1 and already had data

**Comment by arc0035** [comment]
fixed on https://github.com/WeBankBlockchain/Data-Stash/tree/dev
